import { ArrowLeft, ArrowRight, CheckCircle2 } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import Footer from "@/components/Footer";

const details: Record<string, { eyebrow: string; title: string; intro: string; points: string[] }> = {
  "ai-workforce": { eyebrow: "AI Workforce", title: "Một hệ thống phối hợp nhiều AI Specialist", intro: "ViralMinds biến các tác vụ riêng lẻ thành một quy trình có đầu vào, đầu ra và điểm phê duyệt rõ ràng.", points: ["Mỗi AI phụ trách một chuyên môn", "Dùng kết quả bước trước cho bước tiếp theo", "Con người kiểm soát các quyết định quan trọng", "Tùy chỉnh theo dữ liệu và cách vận hành của doanh nghiệp"] },
  "research-strategy": { eyebrow: "Research & Strategy", title: "Hiểu đúng trước khi triển khai", intro: "Phân tích thị trường, khách hàng, đối thủ và dữ liệu nội bộ để xác định cơ hội cùng hướng đi phù hợp.", points: ["Market & competitor research", "Customer insight", "Định vị và thông điệp", "Kế hoạch triển khai"] },
  content: { eyebrow: "Content", title: "Nội dung nhất quán trên mọi kênh", intro: "Xây dựng kế hoạch, hỗ trợ sản xuất và điều phối phân phối nội dung phù hợp với thương hiệu.", points: ["Chiến lược nội dung", "Bài viết, hình ảnh và kịch bản", "Lịch nội dung", "Phân phối đa kênh"] },
  "website-conversion": { eyebrow: "Website & Conversion", title: "Biến lượt truy cập thành cơ hội kinh doanh", intro: "Thiết kế hoặc tối ưu website và landing page theo hành trình khách hàng, thông điệp và mục tiêu chuyển đổi.", points: ["Website & landing page", "Cấu trúc chuyển đổi", "Tracking & measurement", "Tối ưu trải nghiệm"] },
  ads: { eyebrow: "Ads", title: "Quảng cáo được theo dõi và tối ưu có định hướng", intro: "Từ nghiên cứu đối tượng, phát triển nội dung quảng cáo đến theo dõi kết quả và đề xuất tối ưu.", points: ["Nghiên cứu đối tượng quảng cáo", "Xây dựng nội dung và biến thể", "Theo dõi kết quả", "Phát hiện bất thường và đề xuất tối ưu"] },
  "growth-analytics": { eyebrow: "Growth & Analytics", title: "Dùng dữ liệu để tìm cơ hội tăng trưởng", intro: "Đo lường hiệu quả, phát hiện điểm nghẽn và đề xuất các thử nghiệm giúp cải thiện chuyển đổi.", points: ["Tổng hợp dữ liệu Marketing", "Phân tích hiệu quả theo kênh", "Phân tích hành trình khách hàng", "Thử nghiệm và tối ưu tăng trưởng"] },
  crm: { eyebrow: "CRM", title: "Chăm sóc đúng khách hàng vào đúng thời điểm", intro: "Chuẩn hóa dữ liệu, phân loại khách hàng tiềm năng và hỗ trợ tự động hóa quy trình chăm sóc.", points: ["Chuẩn hóa dữ liệu khách hàng", "Phân loại khách hàng tiềm năng", "Tự động hóa chăm sóc", "Hỗ trợ quy trình bán hàng"] },
  process: { eyebrow: "Quy trình", title: "Từ mục tiêu đến một hệ thống vận hành", intro: "Bắt đầu từ việc hiểu doanh nghiệp, thiết kế cấu trúc phù hợp và triển khai từng phần có kiểm soát.", points: ["Khảo sát mục tiêu và hiện trạng", "Thiết kế AI Workforce", "Cấu hình dữ liệu và quy trình", "Kiểm thử, chuyển giao và tối ưu"] },
  pricing: { eyebrow: "Chi phí", title: "Minh bạch theo phạm vi và mức sử dụng", intro: "Không ép doanh nghiệp vào một gói công cụ cố định. Chi phí phản ánh đúng phạm vi triển khai và nhu cầu sử dụng thực tế.", points: ["Phí tư vấn & thiết kế", "Phí cấu hình & triển khai", "Chi phí mô hình AI tách riêng", "Có đề xuất chi tiết sau buổi tư vấn"] },
};

export default function Detail() {
  const { slug = "ai-workforce" } = useParams();
  const detail = details[slug] ?? details["ai-workforce"];
  return <div className="min-h-screen bg-viral-bg text-viral-text"><main className="relative overflow-hidden"><div className="absolute inset-0 aurora-bg grid-bg opacity-80"/><div className="container relative z-10 py-10"><Link to="/" className="inline-flex items-center gap-2 text-viral-text-muted hover:text-viral-accent"><ArrowLeft className="w-4 h-4"/>Quay lại trang chính</Link><section className="min-h-[76vh] flex items-center"><div className="grid lg:grid-cols-2 gap-12 items-center w-full"><div><span className="section-label">{detail.eyebrow}</span><h1 className="font-display text-display-lg mt-5">{detail.title}</h1><p className="text-body-lg text-viral-text-muted mt-6 max-w-xl">{detail.intro}</p><a href="/#contact" className="btn-primary mt-8">Trao đổi về nhu cầu của bạn <ArrowRight className="w-5 h-5"/></a></div><div className="glass-panel p-8 md:p-10 rounded-card-xl space-y-5">{detail.points.map((point, i) => <div key={point} className="flex gap-4 items-start p-4 border-b border-white/10 last:border-0"><CheckCircle2 className="w-6 h-6 text-viral-accent shrink-0"/><div><span className="font-mono text-label-sm text-viral-text-subtle">0{i + 1}</span><h2 className="font-display heading-lg mt-1">{point}</h2></div></div>)}</div></div></section></div></main><Footer/></div>;
}
